preload = ~/Pictures/background/nixos/rubik.png
wallpaper = ,~/Pictures/background/nixos/rubik.png

ipc = off
splash = false
disable_splash_rendering = true

wallpaper {
  monitor = DP-3
  path = ~/Pictures/background/nixos/rubik.png
  fit_mode = cover
}

wallpaper {
  monitor = eDP-1
  path = ~/Pictures/background/nixos/rubik.png
  fit_mode = cover
}
