# Type stub for the NixOS VM test driver globals.
#
# The driver (pkgs.testers.runNixOSTest) injects one `Machine` object per
# `nodes.<name>` entry into the testScript's global namespace at runtime, plus a
# handful of module-level helpers. None of these are importable at runtime; this
# stub exists only so pyright resolves the names statically. Test scripts pull
# them in under an `if TYPE_CHECKING:` guard, so nothing here runs.
#
# Only the members we actually use are typed; extend as needed.
from __future__ import annotations

from contextlib import _GeneratorContextManager
from typing import Callable

class Machine:
    def wait_for_unit(self, unit: str, user: str | None = ...) -> None: ...
    def succeed(self, *commands: str, timeout: int | None = ...) -> str: ...
    def fail(self, *commands: str, timeout: int | None = ...) -> str: ...
    def wait_until_succeeds(self, command: str, timeout: int = ...) -> str: ...
    def wait_for_file(self, filename: str, timeout: int = ...) -> None: ...
    def execute(self, command: str) -> tuple[int, str]: ...
    def shell_interact(self) -> None: ...
    def shutdown(self) -> None: ...

# Node defined as `nodes.machine` in the .nix test.
machine: Machine

def start_all() -> None: ...
def subtest(name: str) -> _GeneratorContextManager[None]: ...
